[project]
name = "demo-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-index>=0.14.24",
    "pydantic>=2.13.5",
    "redis>=8.1.0",
    "torch>=2.14.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.29.0",
]

[project.scripts]
demo-python = "demo_python:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
